### ISSUE TITLE
Unknown option: mousescroll=ver:3,hor:4 in nvim 0.7

### ISSUE THREAD

**Issue by jkhoffman** [wuelnerdotexe/human.vim#1]
Setting up a fresh nvim config, thought I'd try your plugin.

Love it, but getting this error on start.

```
Error detected while processing /Users/jefferyhoffman/.local/share/nvim/site/pack/packer/start/human.vim/plugin/human.vim:
line  182:
E518: Unknown option: mousescroll=ver:3,hor:4
```

Looks like this setting is only available in nightly. Which version of nvim does this plugin require?

**Comment by wuelnerdotexe** [comment]
That's right, this option is available from the Nightly version of Neovim. I will look for the patch that implements it and I will do the corresponding validation.

@jkhoffman thanks for reporting it !!

**Comment by wuelnerdotexe** [comment]
Hi @jkhoffman !! - sorry for the wait, I just uploaded an update with the `patch` and its respective validation, which solves this problem.

Please, close it only if the problem is solved.
